name: math_area
description: "A simple Flutter package to calculate the area of common shapes like square, rectangle, circle, and triangle."
version: 0.0.2
homepage: https://github.com/mayurkapilit23/math_area.git

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:


